### ISSUE TITLE
Error transmiting info between transmitter and receptor with sx1280

### ISSUE THREAD

**Issue by tiagodalima00** [maholli/CircuitPython_SX1280#4]
Good afternoon, 
I am using your library for the sx1280 module implemented in a LAMBDA80-24S module from rfsolutions, this is connected by spi to a raspberry pi 3, the scheme is the same for sender and receiver. 
When sending information and later receiving it I am having an error, I send an bytearray b'\x02' and the receiver always receives b'\xab' regardless of the bytearray I send. If I send two bytes (b'\x02\x02') the receiver receives two bytes but always b'\xab\xab'. 
Can you help me?

**Comment by Centipedea** [comment]
I also encountered this problem, how did you solve it?

**Comment by Centipedea** [comment]
> 

I also encountered this problem, how did you solve it?

**Comment by tiagodalima00** [comment]
Hello, i switch to esp32 and to a c++ library and it's work properly.
